# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0002_users_access'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_Posted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Messages_Posted')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_from', to='logreg.Users')),
            ],
        ),
    ]
